name: leaf2mqtt
version: 0.0.3
publish_to: 'none'
dependencies:
  dartnissanconnectna:
    git: https://gitlab.com/tobiaswkjeldsen/dartnissanconnectna
  dartnissanconnect:
    git:
      url: https://github.com/kamiKAC/dartnissanconnect
      ref: v1.0.5
  dartcarwings:
    git: https://github.com/Tobiaswk/dartcarwings
  mqtt_client: ^9.6.1
  logging: ^1.0.1
  package_info_plus: ^4.2.0
environment:
  sdk: '>=2.10.0 <3.0.0'
